[metadata]
name = hydrawall
version = 0.1.0
description = artifically intelligent cyber security suite
long_description = file: README.md
long_description_content_type = text/markdown
author = Ian Malloy
author_email = iamalloy@utica.edu
url = https://github.com/functionals/hydrawall/tree/main
license = Apache 2.0

[options]
packages = find:
python_requires = >=3.6

[options.extras_require]
dev =
    pytest

[options.entry_points]
console_scripts =
    my_command = hydrawall.module:install

[options.package_data]
* =
    *.txt
    *.rst

[options.exclude_package_data]
* =
    *.pyc

[build_system]
requires =
    setuptools >= 42
    wheel
build-backend = setuptools.build_meta
